export * from './nodeStatusPage/nodeStatusPage';
export * from './verifyMessagePage/verifyMessagePage';
export * from './home/home';
export * from './blocks/blocks';
export * from './block-detail/block-detail';
export * from './address/address';
export * from './transaction/transaction';
export * from './broadcast-tx/broadcast-tx';
export * from './pages.module';
