version: "3.6"
services:

  reddcoin-reddcoind:
    container_name: reddcoin-reddcoind
    image: reddcoincore/reddcoind:latest
    build: ./core
    ports:
      - "45443:45443"
      - "45444:45444"
    volumes:
      - "./.reddcoin:/home/reddcoin/.reddcoin"

  reddcoin-insight:
    container_name: reddcoin-insight
    image: reddcoincore/insight:latest
    build: ./reddsight
    ports:
      - 3000:3000/tcp
    environment:
      - BITCOIND_HOST=172.18.0.2
      - BITCOIND_DATADIR=/home/reddcoin/.reddcoin
    volumes:
      - "./.reddsight:/home/reddcoin/.reddsight"
      - "./.reddcoin:/home/reddcoin/.reddcoin"

