name: all

on:
  push:
    branches:
      - master
jobs:
  build-core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: Build Docker Image
        run: docker build ./Docker/core --tag reddcoincore/reddcoind:latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image
        run: docker push reddcoincore/reddcoind:latest

  build-reddsight:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: Build Docker Image
        run: docker build ./Docker/reddsight --tag reddcoincore/insight:latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image
        run: docker push reddcoincore/insight:latest
